### ISSUE TITLE
add lab photo

### ISSUE THREAD

**Issue by oschulte** [sfu-cl-lab/ML-SFU#2]
1. Photos in Carouel

I would suggest using 

    1. the faculty photos we have
    2. a photo from each lab

2. LIbbrecht should be Libbrecht

3. remove "who's next" faculty member

4. move  "Compute Canada provides high-performance cluster computing. The Cedar node, housed at SFU, has 150 GPUs." to 4th box, currently latin.

**Comment by miyunluo** [comment]
Fix some CSS but still some not work on Safari. (I think Safari does not support)

**Comment by oschulte** [comment]
Okay. If it takes too long to support Safari, we can also ask Patrick the developer for help. And the CS support staff. Have you fixed the content already?

**Comment by miyunluo** [comment]
Only photos remains to be changed now, I will do it later.

I have asked Patrick for help, and he does not know how to do with Safari either.

**Comment by oschulte** [comment]
okay thanks for asking Patrick. I'd say let's take it to the department and ask them to help us with Safari and other browsers. Please let me know when the photos are done so I can review.

**Comment by XiangpengHao** [comment]
I don't have an apple machine so not able to debug on it. Can take a look at the specific problem when getting the chance to talk with @miyunluo later. Probably can come up with a workaround.

**Comment by miyunluo** [comment]
I will try to handle Safari issue again tomorrow (Tuesday), and change the photoes as well. Hope I can make all things done.

**Comment by miyunluo** [comment]
Fix the issue for Safari and change the photo.
BTW, no photo found for our CL lab, do you have any photo for me to use?

**Comment by oschulte** [comment]
great! Hm, good point about our lab :-) Shall we get one at coffee social?

**Comment by miyunluo** [comment]
Aha, a good idea👍🏻
